import app.configs.env_loader
from .chroma import (
    CHROMA_HOST,
    CHROMA_PORT,
    CHROMA_SERVER_HOST,
    CHROMA_SERVER_PORT,
    DOCUMENT_CHUNKS_COLLECTION,
    get_chroma_client,
    get_document_chunks_collection,
)
from .db import (
    DATABASE_URL,
    DB_POOL_SIZE,
    DB_MAX_OVERFLOW,
    engine,
    SessionLocal,
    Base,
    get_db,
)
from .kafka import (
    KAFKA_BOOTSTRAP_SERVERS,
    KAFKA_INTERNAL_BOOTSTRAP_SERVERS,
    KAFKA_UI_URL,
    PDF_PROCESSING_TOPIC,
    PDF_INDEXING_TOPIC,
    PDF_INDEX_REQUEST_TOPIC,
    PDF_FETCHED_TOPIC,
    PDF_PARSED_TOPIC,
    PDF_CHUNKED_TOPIC,
    PDF_EMBEDDED_TOPIC,
    PDF_INDEXING_DLQ_TOPIC,
    KAFKA_CONSUMER_GROUP,
    get_kafka_producer,
    stop_kafka_producer,
    create_kafka_consumer,
)
from .redis import (
    REDIS_HOST,
    REDIS_PORT,
    REDIS_URL,
    DEFAULT_CACHE_TTL,
    SESSION_CACHE_TTL,
    get_redis_client,
    get_async_redis_client,
)
from .promethus import (
    PROMETHEUS_PORT,
    PROMETHEUS_ENABLED,
    ZIPKIN_ENDPOINT,
    OTEL_EXPORTER_OTLP_ENDPOINT,
    OTEL_EXPORTER_OTLP_HTTP_ENDPOINT,
    OTEL_SERVICE_NAME,
    setup_prometheus,
)

__all__ = [
    # Chroma
    "CHROMA_HOST",
    "CHROMA_PORT",
    "CHROMA_SERVER_HOST",
    "CHROMA_SERVER_PORT",
    "DOCUMENT_CHUNKS_COLLECTION",
    "get_chroma_client",
    "get_document_chunks_collection",
    # DB
    "DATABASE_URL",
    "DB_POOL_SIZE",
    "DB_MAX_OVERFLOW",
    "engine",
    "SessionLocal",
    "Base",
    "get_db",
    # Kafka
    "KAFKA_BOOTSTRAP_SERVERS",
    "KAFKA_INTERNAL_BOOTSTRAP_SERVERS",
    "KAFKA_UI_URL",
    "PDF_PROCESSING_TOPIC",
    "PDF_INDEXING_TOPIC",
    "PDF_INDEX_REQUEST_TOPIC",
    "PDF_FETCHED_TOPIC",
    "PDF_PARSED_TOPIC",
    "PDF_CHUNKED_TOPIC",
    "PDF_EMBEDDED_TOPIC",
    "PDF_INDEXING_DLQ_TOPIC",
    "KAFKA_CONSUMER_GROUP",
    "get_kafka_producer",
    "stop_kafka_producer",
    "create_kafka_consumer",
    # Redis
    "REDIS_HOST",
    "REDIS_PORT",
    "REDIS_URL",
    "DEFAULT_CACHE_TTL",
    "SESSION_CACHE_TTL",
    "get_redis_client",
    "get_async_redis_client",
    # Prometheus & Observability
    "PROMETHEUS_PORT",
    "PROMETHEUS_ENABLED",
    "ZIPKIN_ENDPOINT",
    "OTEL_EXPORTER_OTLP_ENDPOINT",
    "OTEL_EXPORTER_OTLP_HTTP_ENDPOINT",
    "OTEL_SERVICE_NAME",
    "setup_prometheus",
]
